src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx, src/mocks/data.js
Submit assignment3-1 as the first try
=> Add test codes to todo app

package.json, src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx, src/__fixture__/tasks.js
트레이너님, 
테스트를 어느정도까지 꼼꼼하게 작성해야하는지 감이 안와서ㅠ
중간점검차 input 컴포넌트만 테스트 코드 작성해봤어요~
=> Write test code for TodoList

src/App.test.jsx, src/Input.test.jsx, src/Item.test.jsx, src/List.test.jsx, src/Page.test.jsx
안녕하세요.!
도저히 진행이 안되서 일단 올리고 질문 드립니다.
아래 코드 부분이 input value 값을 넣으려는 의도인데요, 
이 부분이 실행 된 후로도 `input.value` 는 값이 변하지 않더라고요.
어디가 잘못된 걸까요? 구글링 해보고, 이것저것 해봐도 해결이 어렵네요.. 
`fireEvent.change(input, { target: { value: '테스트' } });`
=> target value change is not working

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
이번 과제에서 너무 헤맸어요;;;;;;
- 지금 하고 방법이 맞는지;;;;;;;
- 넘겨지는 handler를 어떻게 테스트 해야하는지
- 아래 에러를 어떻게 해결헤야하는지
`    console.error
Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
in input (created by Input)
in p (created by Input)
in Input (created by Page)
in div (created by Page)
in Page`
=> [ week3/assignment1] 과제 피드백 부탁드립니다.

.eslintrc.js, jest.config.js, package-lock.json, package.json, src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
** Input.test.jsx 코드 작성 중 에러 발생
[문제] Input 값을 fireEvent.change()로 변경하지 못하고 있음.
[문제] 버튼 클릭 이벤트 발생 에러 & value 값을 어떻게 지워야 하는지 감을 잡지 못하고 있음.
** TDD 단계에 따른 Index.test.jsx 테스트 구현 단계(상상)
- value에 '밥먹기' 값이 들어오기를 기대 - 빨강(실패)
- value에 직접 '밥 먹기' 값을 집어넣기 - 초록(성공)
- event를 추가해 value에 값 넣고 비교하기 <- 여기서 헤메는 중...
- '추가' 버튼 클릭 후 value의 값이 초기화되길 기대 - 빨강(실패)
- value에 직접 ' ' 값을 집어넣기 - 초록(성공)
- '추가' 버튼 클릭 이벤트 추가 - 빨강(실패)
- '추가' 버튼 클릭 시 value 값이 지워지도록 하기 - 초록(성공)
=> [3주차|과제1] To-do 테스트 작성하기 코드 리뷰 부탁드립니다.

package-lock.json, package.json, src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
- **Input**
구성요소가 있는지,
onChange, onClick 호출시 handler 메서드가 호출되는지를 테스트 했습니다.
- **List**
tasks가 있을 때와 없을 때를 나누어서 테스트를 작성했습니다.
- **Page**
하위 컴포넌트들이 나오는지를 테스트 했습니다.
- **App**
task를 추가하고 삭제하는 기능을 테스트 했습니다.
테스트가 처음이라 많이 막막했습니다.
- 자식 컴포넌트에서 테스트한 부분을 부모 컴포넌트에서도 테스트 해야할 지 궁금합니다.
- 테스트 작성은 자식 컴포넌트에서 부모 컴포넌트로(bottom -> up 방식)으로 해야할지 그 반대로 해야할 지 궁금합니다.
=> 첫 테스트 코드 추가

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
List 컴포넌트부터 테스트 작성 중입니다.
tasks가 여러 개 일 때는 어떻게 테스트를 할 지 아직 모르겠지만 일단 PR 먼저 하고 방법을 찾아보겠습니다.
=> [week3] todo 테스트 코드 작성

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
모든 컴포넌트에 테스트를 작성해주세요. 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.
=> [3주차 과제1] To-do 테스트 작성하기

src/App.test.jsx, src/Input.test.jsx, src/List.jsx, src/List.test.jsx, src/Page.test.jsx, src/index.test.jsx
----
모든 컴포넌트에 테스트를 작성해주세요. 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.
- if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- switch는 사용하실 수 없습니다.
- let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.
- ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- 모든 인수 테스트를 통과시켜야 합니다.
- 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- 테스트 커버리지 100%를 달성해야 합니다.
----
- Input Component 테스트 추가
- 테스트를 다 구현하지 않은 상태에서 커버리지가 100% 나오는 문제
- getByLabelText 를 두번째 it 콜백 안에서 실행시 못찾는 문제 
```javascript
const { container, getByLabelText } = render((
<Input value={givenValue} onChange={() => {}} />
));
it('renders label, button text', () => {
expect(container).toHaveTextContent('할 일'); …
```
=> Add tests to TodoList - 작업중

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
Input.jsx 테스트 코드 하나 작성완료했습니다.
테스트 코드 작성을 처음하다보니 어떻게 해야 하는 건지 잘 모르겠지만,
영상을 보고 배운대로 제 선에서 최대한 이해하고 적용해서 작성해봤습니다.
다른 것도 조금씩 작성해서 PR 보낼 예정입니다!
과제 하면서 궁금한 점이 생겼습니다.
이미 작성되어있는 Item.test.jsx 에서 task 값이 바뀌더라도 적용되도록 되어 있지 않고 고정되어 있어서 이 단계는 TDD 사이클에서 GREEN 인걸로 생각됩니다. Refactoring 단계로 진행되지 않은 상태가 맞나요? 그렇다면,
이번주 과제는 Item.test.jsx 에서 작성되어진 "GREEN"단계까지 완성한다는 목표로 작성하면 되는 건가요?  혹시 Refactoring 단계로 테스트 코드를 작성하려면 다른 라이브러리를 사용해야되는건가요? 
제가 잘못 생각하고 있다면 조언 부탁드립니다~!
========
Input test code 에서 value={value} 를 처음에 넣고 작성했다가 빼줬습니다.
value 값이 고정되어 있어서, change event가 발생하더라도 값을 변경하지
못하고 그대로 적용이 되는 문제가 생겨서 어떻게 할지 고민하다가 빼줘도input.value로 값을 확인할 수 있어서 빼줬습니다.
다른 방법으로 render 를 여러 번 실행해주는 방법으로 바뀐값을 넣어주면서
실행하는 방법도 생각해봤지만, 코드 중복이 많이 생길 것 같아서
하지 않았습니다.
=> 🎨 Write test code - 작성 진행중

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx, src/simple.test.js
- 모든 컴포넌트에 테스트 작성하기
- 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.
=> Week3_1 Todo create test code

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
=> [Week3][Davidyang2149]Make Test Code - 구현 완료 / 2차 리팩토링 완료

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
안녕하세요^^
현재 Input.jsx 컴포넌트부터 테스트 코드 작성하려고 시도 중입니다.!
감사합니다 ㅎ.ㅎ
=> week3-1 make todo app test

README.md, src/App.test.jsx, src/Input.test.jsx, src/Item.test.jsx, src/List.test.jsx, src/Page.test.jsx
- 모든 컴포넌트에 테스트를 작성한다.
- App.text.jsx
- List.test.jsx
- Item.test.jsx
- Input.test.jsx
- Page.test.jsx
- task 입력시 task의 title과 버튼이 추가되었는 지 확인
- 버튼 클릭시 handleClick이 호출되는 지 확인
- tasks 입력시 입력된 task가 모두 출력되는 지 확인
- tasks 입력시 task 순서대로 item이 생성되는 지 확인
- tasks 없을시 '할 일 없어요'이 출력되는 지 확인
- '할 일' 라벨이 출력되는 지 확인
- '추가' 버튼이 있는 지 확인
- value가 없을 때, '할 일을 입력해주세요' placeholder가 출력되는 지 확인
- value가 있을 때, value가 출력되는 지 확인
- input에 입력되었을 때 handleChange가 호출되는 지 확인
- '추가' 버튼 클릭시 handleClick이 호출되는 지 확인   
- 'To-do' Page Title이 출력되는 지 확인
- '추가' 버튼 클릭시 List에 task가 추가 되는 지 확인
- '추가' 버튼 클릭시 Input에 값이 사라지는 지 확인
- input에 입력되었을 때 input의 value가 입력한 값으로 변경되는 지 확인
- '삭제' 버튼 클릭시 List에 특정 task가 삭제 되는 지 확인
=> [Week3] Assignment 1 - Todo List 테스트 코드 작성

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
> 모든 컴포넌트에 테스트를 작성해보자.
그리고, 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해보자!
Make test case for Input component.
> nput 컴포넌트의 `onChange` 테스트를 위해 `fireEvent.change()`를 활용하려고 했으나, 다음과 같은 오류 발생.
> ```
> Expected: "뭐라도 하기"
> Received: ""
> ```
아래와 같이 실행 시, 테스트를 통과하는 것으로 보아 node의 문제 아닌 것으로 확인.
> ```
> inputNode.value = '뭐라도 하기'
> expect(inputNode.value).toBe('뭐라도 하기');
> ```
=> To-do 테스트 작성하기

src/App.test.jsx, src/Input.test.jsx, src/Item.test.jsx, src/List.test.jsx, src/Page.test.jsx
**진행사항**
- Input 컴포넌트에 대한 테스트 작성
**느낀점**
- react testing library API 사용법을 이해하지 못하고 있으며 여기 저기 자료를 참고해서 가져다 쓰기도 힘들었습니다.
**궁금한 점**
- 테스트 케이스마다 반복되는 render함수를 제거하려면 어떻게 해야할까요?  test 외부로 render함수를 옮겨보려고 했는데
에러가 발생하여 일단 테스트 케이스마다 모두 render함수를 넣었습니다.
describe-context-test 구조로 작성할 때, 코드가 어느 위치에 있는지에 따른 접근 범위가 차이가 있는지가 궁금합니다.
예를 들어서 context-test 사이에 render를 정의하고 test 내부에서 사용할 때 에러가 나는 경우도 있고 안나는 경우도 있어서
기준이 무엇인지를 잘 모르겠습니다.
- react testing library 공식문서를 조금 읽어보았지만 내용이 거의 이해가 되지 않았습니다. 조금 쉬운 참고 자료가 있을까요? 
- render 함수에서 반환되는 여러 가지 쿼리함수가 어떤 파라미터를 가지고 사용되는지 등이 정리된 사이트나 문서가 있을까요?
공식문서에서 특정 상황에 대한 예시는 있는데 정리된 것을 못 찾겠습니다.
=> [3주차] To-do 리스트 테스트 작성하기

package-lock.json, src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
1. Input에 test code 작성하기
2. List에 test code 작성하기 
3. Page에 test code 작성하기
4. App에 test code 작성하기
=> Create test to To do App

src/App.test.jsx, src/Input.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
- Input
- List
1. 테스트 케이스 작성 순서가 어떻게 되나요.. 너무 작업을 순서없이 한거 같습니다..
2. 테스트를 어느 수준까지 해야하는지 모르겠습니다.. 예를 들어 클릭 이벤트가 발생했을땐 단순히 클릭되었다는 것까지만 테스트를 하면 되는지? 아니면 클릭 후에 발생되는 함수에 의해 상태 값이 변경되는 것 까지 테스트를 하는 것일까요?..
3. `App` 컴포넌트 같은 경우는 자식 컴포넌트에 `state`와 `state 관리하는 함수`를 `props`로 전달해주는데 `jest.fn()`을 이용해 가짜 함수만 만들어서 전달하면 되나요?... `App` 컴포넌트에서는 무엇을 테스트해야하는지 잘 모르겠습니다.. 그리고 만약 `state`가 변화하는 것을 테스트해줘야 한다면.. 그런 테스트는 어떻게 해야하는지... 방향을 못잡고있습니다 ㅜㅜㅜㅜ
중간중간 코드에 주석으로 궁금한 것을 적어놓았는데 확인 부탁드립니다 !
=> create test case

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
브라우저 화면에서 사람이 test 한다고 가정하여 test code 를 작성했습니다. 
화면상에 출력되는 부분만 test code 를 작성하면 되는지 아니면 react 상태변화 까지 test code 를 작성해야 하는지 의문입니다.
=> Make To-do test  

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
=> Write To-do tests

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
첫 PR이 좀 늦었습니다 ~~
1. App 테스트는 거의 작성하지 못했습니다. App.jsx는 state 1개, 함수 3개, Page 컴포넌트 호출 1개 를 가지고 있는데요.
5개 모두 테스트 대상인지 궁금합니다.
2. 1번과 비슷한 질문입니다. App.jsx에 있는 'handleChangeTitle()' 의 경우 App -> Page -> Input 으로 전달되는데 어디서 테스트해야되나요?
3. Input.test 에서, 30line, 35line 의 주석에 질문을 달아놓았습니다. 좋은 방법이 있을까요 ..??
4. Page.test 는 표시되는 문자열만 검사했습니다. 아마 1번과 2번 질문 답주시는거에 따라 수정 방향을 잡을 수 있을 것 같아요!
=> test 커버리지 채우기

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
목표 
1. 결과물에 테스트 코드를 붙히는 과제지만, 나의 테스트 코드로 부터 결과물이 나올것을 기대하며 작성하기
2. 테스트 코드를 보는것 만으로도 어떻게 사용할지 알 수 있도록 작성한다.
3. 테스트를 위한 테스트(할 필요 없는)인 테스트는 작성하지 않는다.
=> Add Test Code for todo

src/App.test.jsx, src/Input.test.jsx, src/Item.test.jsx, src/List.test.jsx, src/Page.test.jsx
Add to test it is not empty
todo가 있는 경우를 테스트합니다.
=> Test by TDD

package-lock.json, package.json, src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
오랫동안 무얼 해야할지 전혀 갈피를 못잡다가 계속 읽고 정리한 끝에 드디어 약간 무슨 말인지, 뭘해야 하는 건지 깨달아 조금이나마 적어 PR을 보냅니다. 너무 낯설어서 처음엔 TDD 관련 글을 읽어도 읽어도 그냥 낱말들의 나열일 뿐이었는데 그것도 계속 하다보니 약간씩이나마 내용이 들어오네요. 이번 주도 잘 부탁드립니다.
=> Making test codes for todo-app

src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
=> [React 3주차 과제] To-do 테스트 작성하기

package.json, src/App.jsx, src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx, src/tasks.jsx
이번 주 내용은 정말 생소하고 어렵네요! 한 번 미루면 끝없이 밀릴 것 같아 일단 PR부터 날려보았습니다..
브레이크가 많이 걸렸지만 일단 큰 부분으로 나누어 보자면.
1. 매개변수가 없는 App의 테스트 코드 작성법 (app에 있는 함수를 테스트하는게 목표?)
2. 또 다른 컴포넌트를 return하는 컴포넌트의 테스트 코드 작성법 
입니다. 일단 공식문서 붙들고 열심히 해 보겠습니다..
=> [3강 테스트] 투두앱 컴포넌트 테스트 코드 작성하기

src/App.jsx, src/App.test.jsx, src/Input.test.jsx, src/Page.test.jsx
안녕하세요!
일단 간단한 컴포넌트부터 테스트를 작성합니다!
테스트 할 때 마다 궁금했는데, 테스트 문법은... 어느 테스트 도구를 쓰든 동일한 문법인가요?!
그리고 react-testing-library 에서 제공하는 api들이 많아보이는데, 언제 어떤것을 적절하게 써야할지 아직 감이 잘 오지 않습니다 ㅠㅠ
=> 과제 1 - To-do 테스트 작성하기

babel.config.js, src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
아직 과제 진행 중인데, 미리 PR 보내드립니다~~💪
`TDD`가 처음이라 많이 어색하네요 ...😅
=> [React 7기 고영욱] 3주차 과제 제출 합니다.

src/App.test.jsx, src/Input.test.jsx, src/Item.test.jsx, src/List.test.jsx, src/Page.test.jsx
테스트 코드 작성이 처음이라 공식 문서를 봐도 잘 이해가 안돼서
강의 기준으로 최대한 따라 하려고 노력했는데 확인 부탁 드려요!
=> [React 7기_신현준] 3강 과제 1

babel.config.js, src/App.test.jsx, src/Input.test.jsx, src/List.test.jsx, src/Page.test.jsx
공식 문서 및 관련 자료들을 찾아서 읽어보고 이해하는 중입니다. 😰 
아직 많은 내용을 작성하진 못했지만 과제 기간동안 꾸준히 추가해보겠습니다. ;)
=> [리액트 7기 표후동] 3주차 과제 1 - To-do 테스트 작성하기

package.json, src/App.test.jsx, src/Input.test.jsx, src/Item.test.jsx, src/List.test.jsx, src/Page.test.jsx
언녕하세요 리뷰어님~ 이번 과제 리뷰도 잘 부탁드립니다~
Test를 작성하면서 중복되는 Test가 많이 생기는 느낌을 받았습니다. ex) App에서 render테스트를 하고, Page에서도 render 테스트를 진행.
불필요한 중복 테스트를 방지하기 위해 어떤 방법을 사용할 수 있을까요? 커버리지 100%를 달성하는게 항상 의미가 있는 행동일까요?
---
=> [React 7기] 조윤호 3주차 unit test 작성하기
